#!/bin/bash

if [[ -z $1 ]]; then
    echo "Usage: $0 go"
    echo "  (as root, sudo ok)"
    echo "  Installs Debian package 'rakudo'."
    exit
fi

# run as root
if [[ $EUID != 0 ]]; then
    echo "Please run as root"
    exit
fi
  
apt-get install rakudo
